[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[workspace]
memebers = [
  "aoc2024",
]

[[bin]]
name = "day1"
path = "src/day1.rs"

[lib]
name = "aoc2024"
path = "src/lib.rs"

[dependencies]
